### ISSUE TITLE
[Feature Requests] Wrap Source-code

### ISSUE THREAD

**Issue by Singond** [radenka/bp-text-overleaf#1]
I propose to keep the line length shorter than some specified maximum value, like 80 or 120 characters, to improve readability of the source code.

Even in 2019, it is advantageous to set a maximum length of lines in source code. While an IDE can automatically wrap long lines visually, they are not wrapped in the raw file. Viewing the source code in terminal, some text editors or here, on Github, for example, shows the lines without automatic wrapping and requires a great deal of horizontal scrolling, which disrupts reading.

**Comment by radenka** [comment]
*That moment when you realize that your supervisor is not the only one who keeps an eye on your thesis*
Btw, hello there!

**Comment by Singond** [comment]
Oh, the joys of open-source…
Wish you good luck with the rest of the thesis. :-)
